image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000 # React App
    onOpen: open-preview
  - port: 3001 # Backend - Json Server
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - coenraads.bracket-pair-colorizer
    - csstools.postcss
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - esbenp.prettier-vscode
    - irongeek.vscode-env
    - johnpapa.winteriscoming
    - johnpapa.vscode-peacock
    - msjsdiag.debugger-for-chrome
    - paulmolluzzo.convert-css-in-js
    - vscode-icons-team.vscode-icons
    - zhuangtongfa.material-theme